service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:us-east-1:090571928722:table/products
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:us-east-1:090571928722:table/stocks
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]
    - Effect: Allow
      Action:
        - sns:*
      Resource:
        Ref: SNSTopic

  stage: sat
  region: us-east-1

package:
    individually: true

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: ./functions/getProductsList/handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: ./functions/getProductById/handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true

  createProduct:
    handler: ./functions/createProduct/handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true

  catalogBatchProcess:
    handler: ./functions/catalogBatchProcess/handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: create-product-queue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: create-product-topic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: superbanger5000@gmail.com
        TopicArn:
          Ref: SNSTopic
