service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:us-east-1:090571928722:table/products
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: arn:aws:dynamodb:us-east-1:090571928722:table/stocks

  stage: sat
  region: us-east-1

package:
    individually: true

plugins:
  - serverless-webpack

functions:
  getProductsList:
    handler: ./functions/getProductsList/handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: ./functions/getProductById/handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true

  createProduct:
    handler: ./functions/createProduct/handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
