service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: sat
  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource: arn:aws:s3:::shop-product-files
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::shop-product-files/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:us-east-1:090571928722:create-product-queue

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'

functions:
  importProductsFile:
    handler: ./functions/import-products-file/handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:090571928722:function:authorization-service-sat-basicAuthorizer
            type: TOKEN
            resultTtlInSeconds: 0
            identityValidationExpression: Basic (.*)

  importFileParser:
    handler: ./functions/import-file-parser/handler.importFileParser
    events:
      - s3:
          bucket: shop-product-files
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
